# Generated by Django 4.2.4 on 2023-09-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_remove_feedbacks_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacks',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
